#   ~/.bash_profile  : Set up bash command line nicely
#

export PATH=.:$HOME/bin:$PATH

# Set prompt
export PS1="\W} "

# Ignore DS_Store files when using bash autocomplete
export FIGNORE=DS_Store

# Enhance the 'cd' command; push old directories onto a stack.
# These additional commands are now available:
#   f    : flip between current and last directory
#   p    : return (pop) to last directory
#
pushd()
{
  if [ $# -eq 0 ]; then
    DIR="${HOME}"
  else
    DIR="$1"
  fi

  builtin pushd "${DIR}" > /dev/null
}

pushd_builtin()
{
  builtin pushd > /dev/null
}

popd()
{
  builtin popd > /dev/null
}

GITHUB="$HOME/github_projects"

alias cd='pushd'
alias p='popd'
alias f='pushd_builtin'
alias ls="ls -l"
alias makeexe="chmod u+x"
alias mv="mv -i"
alias show="unzip -l"
alias hist="history | cut -c 8-"   # Show history without line numbers

# Remove duplicate entries from PATH
#
PATH=`awk -F: '{for(i=1;i<=NF;i++){if(!($i in a)){a[$i];printf s$i;s=":"}}}'<<<$PATH`
