package ml.feed;

/**
 * Object representing work generated by producer, manipulated by
 */
public class Obj {

  public Obj(int id) {
    this.id = id;
  }

  public boolean defined() {
    return id != 0;
  }

  public boolean isNull() {
    return !defined();
  }

  public int id;
  public int used;

  public static final Obj NULL = new Obj(0);
}
